/*
 * This source file was generated by the Gradle 'init' task
 */
package catalogic;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

class CatalogicTest {
    @Test void appHasAGreeting() {
        Catalogic classUnderTest = new Catalogic();
        assertNotNull(classUnderTest);
    }
}
